### ISSUE TITLE
Improve the error messages

### ISSUE THREAD

**Issue by macartur** [kytos/mef_eline#22]
Change error messages 'Invalid arguments' to 'uni_a required'.

**Comment by viniciusarcanjo** [comment]
Since this is supposed to be a small fix, let's take a chance and enhance all the generic raised TypeErrors, like this one: https://github.com/kytos/mef_eline/blob/master/main.py#L37-L39. Maybe we could break this down in three steps and raising the TypeError accordingly like "uni_a is none", "uni_z is none", "Invalid name".  On these lines, https://github.com/kytos/mef_eline/blob/master/main.py#L40-43, maybe we could use "Invalid uni_a", "Invalid uni_z".  

Also, if the user specifies an invalid UNI we should let him know that either the interface or the VLAN is not available. Currently, the is_valid method only validates the tag. The user can request an EPL with an unexisting port, for example. It would be nice for the user to know that the port doesn't exist.

Let me know what you all think.
