### ISSUE TITLE
VLAN range pool settings configuration

### ISSUE THREAD

**Issue by viniarck** [kytos/mef_eline#86]
@beraldoleal  @hdiogenes @ajoaoff , at ESnet, we're only supposed to use a specific range of VLANs to provision the EVCs, which is an issue since currently the code highlighted bellow assumes the entire VLAN range from 1 to 4095 is available:

https://github.com/kytos/kytos/blob/master/kytos/core/interface.py#L90

I believe we should figure out a way to make the VLAN range pools of interfaces configurable. The major design question is, since these attributes belong to the `Interface` class:

1 - Should we allow NApps to monkey patch core Interface attributes on `kytos.core.interface.*`?
2 - Should we provide configurations on `kytos.conf` for the user to define these kind of attributes? Since, initially for example, the user might want that globally, regardless of any NApp?

- Maybe we can provide metadata configuration on `kytos.conf` to override this? But I'm wondering where the most appropriate place for this is, if it's supposed to reside on `kytos.conf` or in the `settings.py` of the NApps.

Let me know what you guys think.

**Comment by hdiogenes** [comment]
At first, I'd say we should avoid the monkey patch route.

Could you provide us with some examples on how we could represent those options in `kytos.conf` and `settings.py`? I think that would make it easier for us to decide between those options.

**Comment by viniarck** [comment]
Yep. I'll prototype them both in the next week.

**Comment by jab1982** [comment]
This capability is mandatory because in multiple cases NNIs won't be connected directly and the service provider in the middle will provide/support a VLAN range. This issue could be overcome with a few approaches: (1) create an individual VLAN pool per NNI; and (2) add a second VLAN tag (QinQ) where the outer most VLAN would be the S-VID (service provider VLAN ID). Implementing #2 might be complex when just one forwarding table exists. I've opened a new issue for us to address it in the future: https://github.com/kytos/flow_manager/issues/62

**Comment by beraldoleal** [comment]
@viniarck I agree with @hdiogenes , we should avoid monkey patch route. Let's go with the second option.

Do you have updates on this?

@jab1982 good. Thanks, man.

**Comment by viniarck** [comment]
@beraldoleal, just opened this PR recently, it's ready to be reviewed, it's been implemented with option number 2 in mind like we discussed https://github.com/kytos/kytos/pull/840/files
